# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['run.py'],
    pathex=['src'],
    binaries=[],
    datas=[
        ('fonts/arial.ttf', 'fonts'),
        ('fonts/arialbd.ttf', 'fonts'),
        ('fonts/DejaVuSans.ttf', 'fonts'),
        ('fonts/DejaVuSans-Bold.ttf', 'fonts'),
        ('simge.ico', '.'),
	('offline_data.db', '.')
    ],
    hiddenimports=[
        'customtkinter',
        'tkinter',
        'PIL',
        'PIL._imagingtk',
        'PIL.ImageTk',
        'requests',
        'fpdf',
        'src.main',
        'src.windows.login_window',
        'src.windows.register_window',
        'src.windows.ogrenci_editor_popup',
        'src.windows.ogrenci_detay_popup',
        'src.windows.ogrenci_secme_popup',
        'src.windows.deneme_detay_window',
        'src.windows.deneme_editor_window',
        'src.windows.soru_cozum_editor_window',
        'src.windows.program_ayarlari_window',
        'src.core.utilities',
        'src.core.ogrenci_takip_app',
        'winreg',
        'pystray',
        'tkcalendar'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='run',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='simge.ico',
)